<?php

namespace ContainerSCAhROI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToastService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\Toast' autowired service.
     *
     * @return \App\Twig\Components\Toast
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Toast.php';

        $container->factories['App\\Twig\\Components\\Toast'] = function ($container) {
            return new \App\Twig\Components\Toast();
        };

        return $container->factories['App\\Twig\\Components\\Toast']($container);
    }
}
