<?php

namespace ContainerKePkdDO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCounterComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\CounterComponent' autowired service.
     *
     * @return \App\Twig\Components\CounterComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/CounterComponent.php';

        $container->factories['service_container']['App\\Twig\\Components\\CounterComponent'] = function ($container) {
            return new \App\Twig\Components\CounterComponent();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\CounterComponent']($container);
    }
}
