<?php

namespace ContainerKePkdDO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiveCounterComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\LiveCounterComponent' autowired service.
     *
     * @return \App\Twig\Components\LiveCounterComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/LiveCounterComponent.php';

        $container->factories['App\\Twig\\Components\\LiveCounterComponent'] = function ($container) {
            return new \App\Twig\Components\LiveCounterComponent();
        };

        return $container->factories['App\\Twig\\Components\\LiveCounterComponent']($container);
    }
}
