<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSCAhROI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSCAhROI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSCAhROI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSCAhROI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSCAhROI\App_KernelDevDebugContainer([
    'container.build_hash' => 'SCAhROI',
    'container.build_id' => 'b2f8d98b',
    'container.build_time' => 1759049858,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSCAhROI');
